model:
  type: TriVAE
  point_emb_dim: 48
  padding: 0.1
  encoder:
    plane_reso: 128
    plane_latent_dim: 32
    latent_dim: 32
    unet:
      depth: 4
      merge_mode: concat
      start_filts: 32
      output_dim: 64
  decoder:
    plane_reso: 128
    latent_dim: 32
    n_blocks: 5
    query_emb_dim: 48
    hidden_dim: 128
    unet:
      depth: 4
      merge_mode: concat
      start_filts: 64
      output_dim: 32
dataset:
  type: Occ
  category: chair
  data_path: ???
  surface_size: 20000
  num_samples: 2048